### ISSUE TITLE
Cesium token doesn't work

### ISSUE THREAD

**Issue by aminissn** [giswqs/mapwidget#10]
I am using Anaconda (Python3.7) on Windows and mapwidget 0.1.2. I can use it with Mapbox but with CESIUM I get the following error: TraitError: The 'token' trait of a Map instance expected a unicode string, not the NoneType None.
 
I basically followed your tutorial and set os.environ['CESIUM_TOKEN'] to my newly generated token.

**Comment by giswqs** [comment]
You can use the token parameter when creating the map. See https://github.com/giswqs/mapwidget/issues/8#issuecomment-1479643442

**Comment by aminissn** [comment]
it works. thanks!
